name: AllergyLab CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build images
      run: |
        cd Part7a
        docker build -t ${{ secrets.DOCKER_USERNAME }}/al-app:latest -f ./app.
        docker build -t ${{ secrets.DOCKER_USERNAME }}/al-email:latest -f ./email.
        docker build -t ${{ secrets.DOCKER_USERNAME }}/al-db-loader:latest -f ./db-loader.